import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HaileGebriel",
  description: "Generated by HaileGebriel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute='class' enableSystem defaultTheme="system">
        <main className="font-sans min-h-screen min-w-screen flex flex-col items-center pb-10 px-8 sm:px-20 md:px-28 transition-all duration-3000">
        <NavBar/>
        {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
